### ISSUE TITLE
cannot find manifest (custom build folder)

### ISSUE THREAD

**Issue by balcy** [bhdouglass/clickable#11]
my setup is the following:

`{
  "dir": "../../click_build/myAppName",
  "template": "pure-qml-cmake",
  ...}
`
- the project dir is ~/click/myAppName
- the build dir is ~/click_build/myAppName
- the project dir has manifest.json.in (so manifest.json is only in the build dir)

if I run clickable I get the message:
**Could not find manifest.json**

If I use the default build dir (which is the sub-folder "build") the problem is gone.

Looking at the code it looks like only the cwd is searched, but not the build dir
`def find_manifest(cwd, temp_dir=None, build_dir=None):` (39-47)

this is rather low prio for me, I just wanted to mention it.
Chris

thank you for creating the tool, it is really useful !

**Comment by bhdouglass** [comment]
Looks like your PR fixed this, thanks! I usually don't have my build dir outside of my source dir, so I missed this in my testing.
