### ISSUE TITLE
snap confine issues

### ISSUE THREAD

**Issue by vadrian89** [bhdouglass/clickable#15]
Whenever trying any command after clickable setup-lxd I get 

> snap-confine has elevated permissions and is not confined but should be. Refusing to continue to avoid permission escalation attacks

snap / distro version
>snap --version    
snap    2.29.3  
snapd   2.29.3  
series  16  
ubuntu  16.04  
kernel  4.10.0-38-generic

**Comment by bhdouglass** [comment]
Did you install it as a classic snap (`snap install --force-dangerous --classic`)?

**Comment by vadrian89** [comment]
Yes, I did.

Pe 16 nov. 2017 2:35 a.m., "Brian Douglass" <notifications@github.com> a
scris:

**Comment by bhdouglass** [comment]
Interesting, I'll have to take a look. In the meantime, have you tried the non-snap install?

**Comment by vadrian89** [comment]
will try

**Comment by vadrian89** [comment]
Installing through the UBports tutorial worked.

**Comment by bhdouglass** [comment]
Awesome! I'll still look into this issue.

**Comment by bhdouglass** [comment]
@vadrian89 with the changing of the default from lxd to docker, can you try this again and see if you run into the same issue?

**Comment by vadrian89** [comment]
Will try to do until this weekend.

**Comment by vadrian89** [comment]
Hi Brian,
Sorry I haven't replied, but I couldn't get my hands into doing anything on my laptop the last couple of weeks, the holidays kept me more busy than normal periods.  
I promise I will test it as soon as I am able, but that would mean from next week.   
Happy Holidays.

**Comment by bhdouglass** [comment]
No rush, check it when you can!

**Comment by bhdouglass** [comment]
Closing this issue as I've deprecated usage of the snap.
