### ISSUE TITLE
template generator

### ISSUE THREAD

**Issue by lduboeuf** [bhdouglass/clickable#19]
hello,

any plan to make a `clickable init` that make easy to start with UT app developement ?
or maybe just links to template repos would be enough. 
thank you for your work :)

**Comment by bhdouglass** [comment]
Yes, this is planned! I want to have a few different templates available to use and you would just need to run something like `clickable init` and choose what you want to use.

**Comment by lduboeuf** [comment]
:+1:

**Comment by bhdouglass** [comment]
I've just added this in v3.0.0. It's not available just yet in the ppa, but will be as soon as the launchpad build service comes back up.
