### ISSUE TITLE
checking dependencies with --container-mode does not work

### ISSUE THREAD

**Issue by balcy** [bhdouglass/clickable#24]
My clickable.json file contains a dependency.
I've started the following command inside the docker container:
`root@70542f133e2f:/home/chris/git/fahrplan# clickable --container-mode --debug`

and get

Checking dependencies
Traceback (most recent call last):
  File "/usr/local/bin/clickable", line 1161, in <module>
    getattr(clickable, COMMAND_HANDLERS[command])()
  File "/usr/local/bin/clickable", line 688, in build
    self.setup_dependencies()
  File "/usr/local/bin/clickable", line 423, in setup_dependencies
    self.check_docker()
  File "/usr/local/bin/clickable", line 480, in check_docker
    status = subprocess.check_output(shlex.split('docker ps'), stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by JBBgameich** [comment]
Clickable should set up its own docker container, you dont need to start it in one

**Comment by balcy** [comment]
yes I know, but --container-mode is for running commands inside the container, isn't it ?
It is the container clickable/ubuntu-sdk:15.04-armhf that I used for it.
My real use case is building an app inside a libertine container on the phone, there I also could use the "--container-mode" flag.

**Comment by bhdouglass** [comment]
Container mode is intended to allow using clickable with continuous integration platform or similar. So it should work in this situation.

I do see the issue and will roll out a fix soon.

**Comment by balcy** [comment]
cool thanks, for me there's no hurry : )

**Comment by bhdouglass** [comment]
I've fixed this in v3.1.0, let me know if it works for you! https://github.com/bhdouglass/clickable/releases/tag/v3.1.0

**Comment by balcy** [comment]
hi, yes works now in libertine and inside docker.
Just a little thing: The dependency cannot detect, that the dependency is already installed for --container-mode and chroot, because the command containing a pipe is not properly executed, I've made https://github.com/bhdouglass/clickable/pull/25 for this
