### ISSUE TITLE
Asking for root to start docker

### ISSUE THREAD

**Issue by gabriel-lucas** [bhdouglass/clickable#27]
Clickable is asking for root password.

$ clickable --version
clickable 3.1.0

$clickable setup-docker
Asking for root to start docker
Setup has already been completed

$clickable 
Asking for root to start docker
Asking for root to start docker
Command '['docker', 'ps']' returned non-zero exit status 1

Similar to this issue.
https://github.com/bhdouglass/clickable/issues/20

**Comment by bhdouglass** [comment]
Is your user part of the docker group? And have you restarted or logged out since you did the first setup?

**Comment by gabriel-lucas** [comment]
Thanks @bhdouglass !
I restarted the session and it kind of work :)

now I´m facing a different error. should I fill other issue?
Unable to start app 'nameOfApp'  AppID is empty

**Comment by bhdouglass** [comment]
Awesome, I'm glad that worked!

I would say file another issue, that way if other users have similar issues it will be easier to find. If you don't mind including the output of clickable that got you to that point, and the clickable.json you are using that would be great.
