### ISSUE TITLE
clickable  -> Unable to start app ' ': AppID is empty

### ISSUE THREAD

**Issue by gabriel-lucas** [bhdouglass/clickable#28]
**What happened:** 
When clickable is executed, the app does not get installed in the phone.

**What I expected to happen: **
The app should install in the phone.

**Steps to reproduce it:** 
1. create a template: clickable init.
2. Run clickable.

Logs

$ clickable init
Available app templates:
[1] pure-qml-cmake - Pure QML App (built using CMake)
[2] cmake - C++/QML App (built using CMake)
[3] python-cmake - Python/QML App (built using CMake)
[4] html - HTML App
[5] webapp - Simple Webapp
Choose an app template [1]: 2
Generating new app from template: C++/QML App (built using CMake)
You've cloned /home/pc/.cookiecutters/ut-app-cmake-template before. Is it okay to delete and re-clone it? [yes]: 
title [App Title]: testApp
description [A short description of your app]: This is a test app.
app_name [appname]: testApp
app_full_name [appname.yourname]: testApp.myname
plugin_name [PluginName]: testAppPlugin
version [1.0.0]: 1.0.0
maintainer_name [Your FullName]: me
maintainer_email [email@domain.org]: me@me.org
Select open_source_license:
1 - GNU General Public License v3
2 - MIT license
3 - BSD license
4 - ISC license
5 - Apache Software License 2.0
6 - Not open source
Choose from 1, 2, 3, 4, 5, 6 [1]: 
Your new app has been generated, go to the app's directory and run clickable to get started

Connect pc and phone

$ clickable 
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/arm-linux-gnueabihf-gcc
-- Check for working C compiler: /usr/bin/arm-linux-gnueabihf-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/arm-linux-gnueabihf-g++
-- Check for working CXX compiler: /usr/bin/arm-linux-gnueabihf-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Gettext: /usr/bin/msgmerge (found version "0.19.2") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pc/Software/UBports/apps/screenRecorder/build
Scanning dependencies of target screenRecorder.desktop
Scanning dependencies of target screenRecorder.gabriellucas.pot
Scanning dependencies of target name_automoc
[ 16%] [ 33%] [ 50%] Merging translations into screenRecorder.desktop...
Generating translation template
Automatic moc for target name
Wrote screenRecorder.desktop.in.h
Merging translations into screenRecorder.desktop.
[ 50%] Built target screenRecorder.desktop
[ 50%] Built target screenRecorder.gabriellucas.pot
Generating moc_name.cpp
Generating moc_plugin.cpp
[ 50%] Built target name_automoc
Scanning dependencies of target name
[ 66%] [ 83%] [100%] Building CXX object plugins/name/CMakeFiles/name.dir/plugin.cpp.o
Building CXX object plugins/name/CMakeFiles/name.dir/name.cpp.o
Building CXX object plugins/name/CMakeFiles/name.dir/name_automoc.cpp.o
Linking CXX shared module name/libname.so
[100%] Built target name
[ 16%] Merging translations into screenRecorder.desktop...
Merging translations into screenRecorder.desktop.
[ 16%] Built target screenRecorder.desktop
[ 33%] Generating translation template
Wrote screenRecorder.desktop.in.h
[ 33%] Built target screenRecorder.gabriellucas.pot
[ 50%] Automatic moc for target name
[ 50%] Built target name_automoc
[100%] Built target name
Install the project...
-- Install configuration: ""
-- Installing: /home/pc/Software/UBports/apps/screenRecorder/build/tmp//manifest.json
-- Installing: /home/pc/Software/UBports/apps/screenRecorder/build/tmp//screenRecorder.apparmor
-- Installing: /home/pc/Software/UBports/apps/screenRecorder/build/tmp//qml
-- Installing: /home/pc/Software/UBports/apps/screenRecorder/build/tmp//qml/Main.qml
-- Installing: /home/pc/Software/UBports/apps/screenRecorder/build/tmp//assets
-- Installing: /home/pc/Software/UBports/apps/screenRecorder/build/tmp//assets/logo.png
-- Installing: /home/pc/Software/UBports/apps/screenRecorder/build/tmp//screenRecorder.desktop
-- Installing: /home/pc/Software/UBports/apps/screenRecorder/build/tmp/lib/arm-linux-gnueabihf/name/libname.so
-- Installing: /home/pc/Software/UBports/apps/screenRecorder/build/tmp/lib/arm-linux-gnueabihf/name/qmldir
Successfully built package in './screenRecorder.gabriellucas_1.0.0_armhf.click'.
[100%] /home/phablet/screenRecorder.gabriellucas_1.0.0_armhf.click
Installing files              [=========================]         
Finished                      [=========================]         
Installing files              [=========================]         
Starting                      [=========================]         
Finished                      [=========================]         
Installed   	screenRecorder.gabriellucas-1.0.0.armhf (installed:click,removable=1,app_name=screenRecorder)	summary goes here

 (process:9330): WARNING : Unable to start app 'screenRecorder.gabriellucas_screenRecorder_1.0.0': AppID is empty

**Software Version:**
SO: Ubuntu 16.04 (r205)
clickable 3.1.0

**Comment by bhdouglass** [comment]
Do you have the source for this app posted somewhere? I'm not sure what's going on.

**Comment by cibersheep** [comment]
Oh, it might be this: ` app_full_name [appname.yourname]: testApp.myname`
Could you try with appname.youname in lowercase?

**Comment by bhdouglass** [comment]
@cibersheep is that actually a requirement? If so I can force it to be lowercase in the templates.

**Comment by cibersheep** [comment]
I'm not totally sure, but I can test

**Comment by cibersheep** [comment]
Ok. That was a quick test.
You never trust my memory.
Yes: lower case mandatory
```
- lint:pkgname_valid
	'quiXe.cibersheep' not properly formatted
```

**Comment by bhdouglass** [comment]
Thanks! I'll make that a part of the templates.

**Comment by bhdouglass** [comment]
I've updated the templates, @gabriel-lucas does making the app's full name lowercase only fix your issue?

**Comment by gabriel-lucas** [comment]
Hi @bhdouglass 
I tested the update and know it works.
Well done, thanks!

**Comment by bhdouglass** [comment]
Awesome, you're welcome!
