### ISSUE TITLE
Can't start html5 app on desktop

### ISSUE THREAD

**Issue by cibersheep** [bhdouglass/clickable#29]
I have created an html5 app with no problem.
When I tried to test it on desktop
`clickable --desktop`
compiles it but gives this error:
```
Skipping install, running in desktop mode
bash: webapp-container: command not found
Command '['docker', 'run', '-v', 
[...]
 'clickable/ubuntu-sdk:15.04-amd64', 'bash', '-c', 'webapp-container --app-id=tankball.cibersheep $@ www/index.html\n']' returned non-zero exit status 127
```
So, I guess webapp-container it's not installed in docker

**Comment by gabriel-lucas** [comment]
I can confirm a similar case.

**Logs**
/UBports/apps/testhtml$ clickable --desktop
Skipping kill, running in desktop mode
Copied files to temp directory for click building
Successfully built package in './testhtml.gabriel_1.0.0_all.click'.
Skipping install, running in desktop mode
bash: webapp-container: command not found
Command '['docker', 'run', '-v', '/home/pc/Software/UBports/apps/testhtml:/home/pc/Software/UBports/apps/testhtml', '-v', '/tmp/.X11-unix:/tmp/.X11-unix', '-v', '/tmp/.docker.xauth:/tmp/.docker.xauth', '-e', 'XAUTHORITY=/tmp/.docker.xauth', '-e', 'DISPLAY=:0', '-e', 'QML2_IMPORT_PATH=/home/pc/Software/UBports/apps/testhtml/build/tmp/lib/x86_64-linux-gnu', '-e', 'LD_LIBRARY_PATH=/home/pc/Software/UBports/apps/testhtml/build/tmp/lib/x86_64-linux-gnu', '-e', 'PATH=/bin:/usr/bin:/home/pc/Software/UBports/apps/testhtml/build/tmp/bin:/home/pc/Software/UBports/apps/testhtml/build/tmp/lib/x86_64-linux-gnu/bin:/home/pc/Software/UBports/apps/testhtml/build/tmp', '-w', '/home/pc/Software/UBports/apps/testhtml/build/tmp', '-u', '1000', '--rm', '-i', 'clickable/ubuntu-sdk:15.04-amd64', 'bash', '-c', 'webapp-container --app-id=testhtml.gabriel $@ www/index.html\n']' returned non-zero exit status 127



**Software Versions:**
ubports N5 16.04 (rev 205)
clickable 3.1.0

**Comment by bhdouglass** [comment]
Fixed! Check out v3.1.2 (currently building in the ppa). I had to add missing cache & config directories.

**Comment by cibersheep** [comment]
Mmmm I get the same error on 3.1.2
Am I doing something wrong?

**Comment by bhdouglass** [comment]
Yeah you might need to update your docker image: `docker pull clickable/ubuntu-sdk:15.04-amd64`

**Comment by cibersheep** [comment]
It works! :D

**Comment by bhdouglass** [comment]
Awesome!

**Comment by ivoxavier** [comment]
Hi, I'm having "kind of similar problem" when trying to run 'clickable --desktop":

`ivo@ivo-Mac:~/new$ clickable --desktop
No clickable.json was found, using defaults and cli args
Auto detected template to be "pure"
Skipping kill, running in desktop mode
Copied files to temp directory for click building
Successfully built package in './new.ivoxavier_0.1_all.click'.
Skipping install, running in desktop mode
Could not desktop file does not exist: "/home/ivo/new/build/tmp/new.ivoxavier.desktop"
`
I just want to check if all the tools works before I start the development of the app

Thanks, and sorry if this is not the right place

**Comment by bhdouglass** [comment]
@ivoxavier it sounds like the path to your desktop file in your manifest.json doesn't match with the actual path of the desktop file.
