### ISSUE TITLE
[Desktop] content-hub

### ISSUE THREAD

**Issue by delijati** [bhdouglass/clickable#33]
I've i try to download (DownloadManger) a file nothing happens while i develop on Desktop. Is it because the `content-hub` is not running in a image and there are no other apps to call aka `gallery-app`, `filemanager-app`?

Can this be fixed maybe with `docker-compose`?

**Comment by bhdouglass** [comment]
Even if I got download manager and content hub working in the container I think you would still run into the issue of not having anywhere to export your files to. In this case it, unfortunately, would be best to do testing on your device.

**Comment by bhdouglass** [comment]
This has been moved to gitlab: https://gitlab.com/clickable/clickable/issues/33
