### ISSUE TITLE
--desktop mode doesn't skip the logs command

### ISSUE THREAD

**Issue by mymike00** [bhdouglass/clickable#35]
If in the `clickable.json` I add `"default": "kill clean build click_build install launch logs"` and run the app with `clickable --desktop`, in the log I see that clickable skips `kill` and `install` because I'm using it on desktop, while it doesn't skip `logs` (that I added) and it report an error.

so my request is to make clickable that skips also the `logs` command while running an app on desktop

**Comment by bhdouglass** [comment]
Fixed in v3.1.5!
