### ISSUE TITLE
question: Clickable qmake with main.cpp 

### ISSUE THREAD

**Issue by FloVanGH** [bhdouglass/clickable#38]
Is it also possible to build a qmake project with a man.cpp instead of the plugin project? If yes, how can I achieve this? I tried it with the qmake build template but it doesn't work.

**Comment by bhdouglass** [comment]
You should be able to do this easily with the "qmake". The OpenStore app is built with qmake and has a main.cpp if you want a reference: https://github.com/UbuntuOpenStore/openstore-app/blob/master/openstore/openstore.pro

**Comment by FloVanGH** [comment]
Thank you that works.

Next question: How could I run a sub project as background task?

**Comment by bhdouglass** [comment]
I'm going to close this since we talked about it in the telegram group.
