### ISSUE TITLE
--desktop mode does not work with nvidia

### ISSUE THREAD

**Issue by jonnius** [bhdouglass/clickable#43]
When I switch to the intel graphics (with prime), `--desktop` works as expected. But when using my nvidia card the `--desktop` mode does not work. I get this error:

```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Unrecognized OpenGL version
Unrecognized OpenGL version
```

card: GeForce 840M
driver: nvidia-384

**Comment by bhdouglass** [comment]
Have you tried the opensource nvidia drivers? I've been told they work.

**Comment by jonnius** [comment]
Indeed. It works with the open source driver nouveau. The issue is only with the proprietary nvidia driver.

**Comment by bhdouglass** [comment]
If you are interested in tinkering with this you might have some luck with this: https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker-plugin

Unfortunately I don't have a way to test this myself so I'm going to close out this issues (as the nouveau drivers work).
