### ISSUE TITLE
AUR package does not register 'clickable' in /usr/[local]/bin 

### ISSUE THREAD

**Issue by luksus42** [bhdouglass/clickable#45]
Hi,
I'm not shure if that should be a normal behaviour, but I had to to create my own simlink in /usr/bin to be able to start clickable  comfortable from the commandline.

Best regards

**Comment by bhdouglass** [comment]
I'm not sure what's the expected behavior there as I didn't write the AUR package, but I've got a question out to the author about this.

**Comment by luksus42** [comment]
Ah ok. I thought by mistake that you were the one who wrote it.

**Comment by tydell** [comment]
After installation package is placed in /opt, but user also have to do some magic - add clickable to PATH, so there is no need to make simlink  (info below is diplayed after installation). I will release new package in day or two, where everything will be done automatically without the user's intervention.

```
To finish installation you have to add clickable to your PATH, read the new .bashrc file and configure docker for clickable:
echo "export PATH=\$PATH:\/opt/clickable" >> ~/.bashrc
source ~/.bashrc
clickable setup-docker
```

**Comment by luksus42** [comment]
thank you very much.

**Comment by bhdouglass** [comment]
@tydell for a better user experience shouldn't the AUR package set up something to allow clickable to work without changing anything? That or have a note about it on the AUR site.

**Comment by tydell** [comment]
Yes, it should. Im working currently at it and will update aur package.

**Comment by bhdouglass** [comment]
Thanks! I've reopened this issue until you have a chance to update the package, just let me know when you do!

**Comment by tydell** [comment]
Aur package is updated. After installation user just need to configure docker for clickable:
clickable setup-docker 
and install cookiecutter package:
pip2 install --user cookiecutter   (due to clickable using python2, unfortunately python-cookiecutter aur package doesn't work properly with clickable).
After clickable instalaltion and these two commands everything works as expected.

**Comment by bhdouglass** [comment]
Thanks @tydell ! Just a heads up that clickable will be switching to python 3 in the near future.
