### ISSUE TITLE
clickable init -> cookiecutter not available

### ISSUE THREAD

**Issue by luksus42** [bhdouglass/clickable#46]
Hi,
on calling `clickable init` I get the response:

> Cookiecutter is not available on your computer, more information can be found here: https://cookiecutter.readthedocs.io/en/latest/installation.html#install-cookiecutter

 
But cookiecutter is there:

```shell
 luke@luke-pc  ~  clickable init     
Cookiecutter is not available on your computer, more information can be found here: https://cookiecutter.readthedocs.io/en/latest/installation.html#install-cookiecutter
 ✘ luke@luke-pc  ~  python        
Python 3.6.4 (default, Jan  5 2018, 02:35:40) 
[GCC 7.2.1 20171224] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> cookiecutter_available = True
>>> try:
...     from cookiecutter.main import cookiecutter
... except ImportError:
...     cookiecutter_available = False
... 
>>> print(cookiecutter_available)
True
>>> 
```

**Comment by bhdouglass** [comment]
From the output you posted, it looks like you have the python 3 version of cookiecutter installed. Currently clickable is still using python 2 (very very soon to change). If you want to use `clickable init` before the update to python 3 you'll need to use `pip2` to install cookiecutter.

**Comment by tydell** [comment]
Because of python2 you have to install cookiecutter by your own. On Archlinux after clickable instalaltion you have to do:
pip2 install --user cookiecutter
Pip2 comes from pip2pkgbuild package (one of clickable dependencies).
