### ISSUE TITLE
--desktop not working with nvidia-390 on Ubuntu 18.14

### ISSUE THREAD

**Issue by ChristianPauly** [bhdouglass/clickable#50]
I am using Ubuntu 18.04 with the standard Ubuntu Gnome desktop. The PPA does not work on 18.04 :-( so I have installed clickable with pip. When I try to test my app with "clickable --desktop" I get this errors:
``
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Unrecognized OpenGL version
Unrecognized OpenGL version
``

Is there any workaround yet?

**Comment by bhdouglass** [comment]
Are you using nvidia?

**Comment by ChristianPauly** [comment]
Yes. But I have tried the --nvidia command, also tried to disable the nvidia drivers with the same experience. However on my intel based Notebook with Ubuntu 18.04 there is the same error :-(

**Comment by bhdouglass** [comment]
Are you using a wayland session or an x org session?

**Comment by ChristianPauly** [comment]
xorg

**Comment by bhdouglass** [comment]
hmm... ok, I would think this would just be an nvidia driver issue except you say the intel machine doesn't work either. Can you try with the nouveau drivers just to check?

**Comment by ChristianPauly** [comment]
Wow okay it works with the nouveau drivers. Okay then the problem seems to be the nvidia-390 and whatever is built in my Macbook. I will try nvidia-340 tomorrow and check which GPU the macbook has. By the way, clickable is a very good job!

**Comment by bhdouglass** [comment]
Awesome! I'm glad that's working for you. If you want to continue using the nvidia drivers you can try installing https://github.com/NVIDIA/nvidia-docker & then using the `--nvidia` option with clickable.
