### ISSUE TITLE
command "clickable logs" fails with missing manifest.json

### ISSUE THREAD

**Issue by fourloop2002** [bhdouglass/clickable#51]
When I run the command it fails with error "Could not find manifest.json".  There is a manifest.json.in file which when linked to manifest,json results in a logfile listing being displayed.

**Comment by bhdouglass** [comment]
Usually `clickable logs` works after you've compiled your app (this is so it can parse the app name & version from the built manifest.json). Do you have a manifest.json in your `build` directory?

**Comment by fourloop2002** [comment]
Yes there is a `build/manifest.json` file.  I ran `clickable logs` command from the parent of the `build` directory where the only file is `manifest.json.in`.

**Comment by fourloop2002** [comment]
Oops wrong button - `noob` error ;-)

**Comment by bhdouglass** [comment]
Ok, can you run `clickable logs --debug` and send me the output?

**Comment by fourloop2002** [comment]
ianl@ianl-H81M-DS2: \~/work/mzanetti/ubtd$ clickable logs --debug
No clickable.json was found, using defaults and cli args
Auto detected template to be "qmake"
Traceback (most recent call last):
  File "/usr/bin/clickable", line 11, in <module>
    load_entry_point('clickable==4.1.0', 'console_scripts', 'clickable')()
  File "/usr/lib/python3/dist-packages/clickable.py", line 1462, in main
    getattr(clickable, COMMAND_HANDLERS[command])()
  File "/usr/lib/python3/dist-packages/clickable.py", line 849, in logs
    log = '~/.cache/upstart/application-click-{}_{}_{}.log'.format(self.find_package_name(), self.find_app_name(), self.find_version())
  File "/usr/lib/python3/dist-packages/clickable.py", line 365, in find_package_name
    package = self.get_manifest().get('name', None)
  File "/usr/lib/python3/dist-packages/clickable.py", line 356, in get_manifest
    return get_manifest(self.cwd, self.temp, self.config.dir)
  File "/usr/lib/python3/dist-packages/clickable.py", line 114, in get_manifest
    with open(find_manifest(cwd, temp_dir, build_dir), 'r') as f:
  File "/usr/lib/python3/dist-packages/clickable.py", line 93, in find_manifest
    raise ManifestNotFoundException('Could not find manifest.json')
clickable.ManifestNotFoundException: Could not find manifest.json

**Comment by fourloop2002** [comment]
The directory listing is:
ianl@ianl-H81M-DS2:\~/work/mzanetti/ubtd$ ls -la
total 100
drwxrwxr-x 6 ianl ianl  4096 May 20 17:05 .
drwxrwxr-x 3 ianl ianl  4096 May 20 17:05 ..
drwxrwxr-x 2 ianl ianl  4096 May 20 17:05 app
drwxrwxr-x 6 ianl ianl  4096 May 20 17:05 .bzr
-rw-rw-r-- 1 ianl ianl   673 May 20 17:05 manifest.json.in
drwxrwxr-x 2 ianl ianl  4096 May 20 17:05 po
drwxrwxr-x 2 ianl ianl  4096 May 20 17:05 shareplugin
-rw-rw-r-- 1 ianl ianl  1034 May 20 17:05 ubtd.pro
-rw-rw-r-- 1 ianl ianl 43695 May 20 17:05 ubtd.pro.user

Hope this helps.

**Comment by bhdouglass** [comment]
So I'm not seeing the build directory in your directory listing, do you have it configured to be somewhere else?

**Comment by fourloop2002** [comment]
I ran the following commands to start from square 1:
`clickable clean`
`clickable`
`clickable logs`

The log displayed and added new entries as I operated the newly installed app on my phone.

So looks to be working.  Just a noob issue.  Thanks for your help.

**Comment by bhdouglass** [comment]
No worries, I might make a better error message that it needs to be built before the logs command can be run.
