### ISSUE TITLE
Errors during setup-lxd

### ISSUE THREAD

**Issue by doniks** [bhdouglass/clickable#6]
I'm trying to install clickable from git under ubuntu xenial. During the setup-lxd step I get loads of errors:

clickable setup-lxd
Going to setup the lxd container
Asking for root to create the lxd container
Creating image with:
framework: ubuntu-sdk-15.04
arch: armhf
Initializing progress tracker
Retrieving image: 1% (3.61MB/s)
[...]
Setting up python3-debian (0.1.22ubuntu1) ...
Setting up python3-click-package (0.4.45+15.04.20160828.1-0ubuntu1) ...
Setting up click (0.4.45+15.04.20160828.1-0ubuntu1) ...
Created symlink from /etc/systemd/user/default.target.wants/click-user-hooks.service to /usr/lib/systemd/user/click-user-hooks.service.
Setting up busybox-initramfs (1:1.22.0-9ubuntu1) ...
Setting up cpio (2.11+dfsg-4.1ubuntu1) ...
update-alternatives: using /bin/mt-gnu to provide /bin/mt (mt) in auto mode
Setting up initramfs-tools-bin (0.103ubuntu15) ...
Setting up libklibc (2.0.3-0ubuntu1) ...
Setting up klibc-utils (2.0.3-0ubuntu1) ...
Setting up initramfs-tools (0.103ubuntu15) ...
update-initramfs: deferring update (trigger activated)
Setting up libapparmor-perl (2.9.1-0ubuntu9.1) ...
Setting up apparmor (2.9.1-0ubuntu9.1) ...
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
/sbin/apparmor_parser: Unable to replace "udm-extractor".  Permission denied; attempted to load a profile while confined?
Warning failed to create cache: usr.lib.ubuntu-download-manager.udm-extractor
/sbin/apparmor_parser: Unable to replace "/usr/bin/mediascanner-service-2.0".  Permission denied; attempted to load a profile while confined?
Warning failed to create cache: usr.bin.mediascanner-service-2.0
/sbin/apparmor_parser: Unable to replace "/sbin/dhclient".  Permission denied; attempted to load a profile while confined?
Warning failed to create cache: sbin.dhclient
/sbin/apparmor_parser: Unable to replace "/usr/lib/*/mediascanner-2.0/mediascanner-extractor".  Permission denied; attempted to load a profile while confined?
Warning failed to create cache: usr.lib.mediascanner-2.0.mediascanner-extractor
/sbin/apparmor_parser: Unable to replace "udm-extractor".  Permission denied; attempted to load a profile while confined?
Warning failed to create cache: usr.lib.ubuntu-download-manager.udm-extractor
/sbin/apparmor_parser: Unable to replace "/sbin/dhclient".  Permission denied; attempted to load a profile while confined?
Warning failed to create cache: sbin.dhclient
/sbin/apparmor_parser: Unable to replace "/usr/bin/mediascanner-service-2.0".  Permission denied; attempted to load a profile while confined?
Warning failed to create cache: usr.bin.mediascanner-service-2.0
/sbin/apparmor_parser: Unable to replace "/usr/lib/*/mediascanner-2.0/mediascanner-extractor".  Permission denied; attempted to load a profile while confined?
Warning failed to create cache: usr.lib.mediascanner-2.0.mediascanner-extractor
sh: echo: I/O error
sh: echo: I/O error
sh: echo: I/O error
sh: echo: I/O error
sh: echo: I/O error
sh: echo: I/O error
sh: echo: I/O error
sh: echo: I/O error
sh: echo: I/O error
sh: echo: I/O error
sh: echo: I/O error
sh: echo: I/O error
sh: echo: I/O error
sh: echo: I/O error
sh: echo: I/O error
sh: echo: I/O error
sh: echo: I/O error
sh: echo: I/O error
Setting up apparmor-easyprof-ubuntu (1.3.20) ...
(may take a while)
Setting up python3-libapparmor (2.9.1-0ubuntu9.1) ...
Setting up python3-apparmor (2.9.1-0ubuntu9.1) ...
Setting up apparmor-easyprof (2.9.1-0ubuntu9.1) ...
Setting up python3-apparmor-click (0.3.8) ...
Setting up click-apparmor (0.3.8) ...
Processing triggers for libc-bin (2.21-0ubuntu4.0.1) ...
Processing triggers for systemd (219-7ubuntu6vividtouch1) ...
Processing triggers for initramfs-tools (0.103ubuntu15) ...
Finished setting up the lxd container

**Comment by doniks** [comment]
Oh, ok. Thanks! It just looked too scary.

About issues building ... well, I'm kinda stuck trying to find/setup some kind of example ... I'm new to UT apps. You don't happen to know a "hello world" like app and clickable.json to try?!

I'm trying 
https://github.com/QtRoS/shorts
with 

```
{
"template": "cmake",
"ssh": "nexus"
}
```

but that complains about all kinds of QT5 stuff missing, like:

```
  By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Core", but
  CMake did not find one.
```

**Comment by bhdouglass** [comment]
Here is my app template that is already set up with clickable: https://github.com/bhdouglass/ut-app-template

Try that one, if it complains about QT stuff too, then I was wrong and your lxd containers is broken.

**Comment by doniks** [comment]
Awesome! That works!

**Comment by bhdouglass** [comment]
Wonderful! Let know if you have any other issues!
