### ISSUE TITLE
Problem with PushHelper

### ISSUE THREAD

**Issue by ChristianPauly** [bhdouglass/clickable#61]
Hi, I have a little problem. I hope you can help me. When I use this example app: https://github.com/ChristianPauly/ut-pushclient-example then push notifications are working fine. This app just sends push to itself and nothing more. For that, there is a hook called "helloHelper" with an apparmor file, an execute .json and a executable helloHelper in python.
When I just build the exactly same app with clickable, this does not work anymore. In the push logs are:
"ERROR can't locate helper for app"
Is this a bug in clickable or am I doing something wrong?
Do I have to add the helloHelper hook to the cmakelists? No idea how to work with cmake. :-(

**Comment by ChristianPauly** [comment]
Sorry!! This is absolutely my fault! After I have read a little bit about cmake I found out that I have to add this three lines to cmakelists.txt

``
install(FILES helloHelper PERMISSIONS OWNER_EXECUTE OWNER_WRITE OWNER_READ DESTINATION ${DATA_DIR})
install(FILES helloHelper.json DESTINATION ${DATA_DIR})
install(FILES helloHelper-apparmor.json DESTINATION ${DATA_DIR})
``

Sorry again!! :-(

**Comment by bhdouglass** [comment]
No worries, I'm glad you got that figured out!
