### ISSUE TITLE
Can't build my app (shorter) for 16.04 desktop

### ISSUE THREAD

**Issue by doniks** [bhdouglass/clickable#62]
repro:

git clone https://github.com/doniks/shorter
cd shorter 
edit like this: https://forums.ubports.com/topic/1215/updating-apps-to-16-04
clickable --sdk 16.04 --desktop > clickable.log 2>&1
wait 
window opens but it stays a small white rectangle. 

I think the relevant part of the log is this: 

WARNING:root:Ignoring missing framework "ubuntu-sdk-16.04"
Successfully built package in './doniks.shorter_4.2_amd64.click'.
non-network local connections being added to access control list
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-'
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
qrc:///qml/shorts-app.qml:298:30: Type SharePage unavailable
qrc:///qml/content/SharePage.qml:3:1: module "Ubuntu.Content" is not installed

I attach the whole log. 

Running it on the device with 
clickable --sdk 16.04 
works ok 
[clickable.log](https://github.com/bhdouglass/clickable/files/2066120/clickable.log)

**Comment by bhdouglass** [comment]
I see libGL errors in there, do you happen to be running nvidia drivers? But that doesn't explain the Ubuntu.Content missing. Does this work when you use the 15.04 SDK?

**Comment by doniks** [comment]
> I see libGL errors in there, do you happen to be running nvidia drivers? 
No. Intel. I am running ubuntu 18.04 with gnome desktop using wayland, in case any of that matters

> But that doesn't explain the Ubuntu.Content missing. Does this work when you use the 15.04 SDK?

Yes. I put .apparmor and manifest back to 15.04 and I can
`clickable --sdk 15.04 --desktop`

I can even `clickable --sdk 15.04`, even though the device is running 16.04!

**Comment by bhdouglass** [comment]
Any chance #63 fixes this?

**Comment by doniks** [comment]
No. unfortunately no change. After that docker pull, I did 

rm -rf shorter
put 16.04 manifest and apparmor back 
clickable --sdk 16.04 --desktop
...
same error about Ubuntu.Content

**Comment by bhdouglass** [comment]
I tried running your app and got this: `qrc:///qml/pages/YadLoginPage.qml:21:1: module "Ubuntu.Web" is not installed`. So there must be some missing dependencies in the container, but that's probably because the upstream meta sdk package is missing stuff. I'll have to look into it more.

**Comment by bhdouglass** [comment]
This is partially blocked by this bug: https://github.com/ubports/ubuntu-touch/issues/699

**Comment by bhdouglass** [comment]
Try out the latest version of the docker container, should fix this problem: `clickable update-docker --xenial`

**Comment by doniks** [comment]
no. same white rectangle

**Comment by bhdouglass** [comment]
Oh actually, the command should be `clickable update-docker --xenial --desktop`
