### ISSUE TITLE
missing qt quick dependencies

### ISSUE THREAD

**Issue by doniks** [bhdouglass/clickable#63]
I'm trying to build an app for 16.04 with qtquick, but I run into missing dependencies. 

I added qml-module-qtquick-controls2 already, but I still get a build failure

repro:

git clone git@github.com:doniks/libertine-tweak-tool.git
cd libertine-tweak-tool 
clickable --sdk 16.04 

->
CMake Warning at CMakeLists.txt:6 (find_package):
  By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Core", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Core" with any
  of the following names:

    Qt5CoreConfig.cmake
    qt5core-config.cmake

  Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
  "Qt5Core_DIR" to a directory containing one of the above files.  If
  "Qt5Core" provides a separate development package or SDK, be sure it has
  been installed.

https://paste.ubuntu.com/p/cDfVxbBDP2/

**Comment by bhdouglass** [comment]
Make sure you have the latest docker container for 16.04 (run `docker pull clickable/ubuntu-sdk:16.04-armhf`) and try again without the extra dependency (and you might want to delete the generated .clickable directory in your repo). If that still fails I'll probably need to tweak the docker images.

**Comment by doniks** [comment]
Yes, after pulling, deleting .clickable and rebuilding it worked.

Thanks!

**Comment by bhdouglass** [comment]
Awesome, you're welcome!
