### ISSUE TITLE
QQC2 desktop application to UT

### ISSUE THREAD

**Issue by lduboeuf** [bhdouglass/clickable#65]
hello,

Let say i have an already running Qt desktop app (QQC2) built with cmake , now i want to build it also for UT. 
What is the easiest way to make it ? 
 A kind of a `clickable init` for an existing project ?

**Comment by bhdouglass** [comment]
There isn't a QQC2 app template (yet, PRs welcome!), but you should be able to use one of the existing cmake/qml templates and add your code to it. And you'll need to use `--sdk=16.04` with clickable because 15.04 (the default) doesn't support QQC2.

**Comment by lduboeuf** [comment]
fine, i've noticed that qqc2 is shipped with 16.04 image so nothing needs to be added to the template. i will try it tomorrow and PR.

**Comment by lduboeuf** [comment]
humm, is QQC2 the next mainstream UI toolkit tomorrow ? If so, we have better to replace all Ubuntu.Components for 16.04

**Comment by bhdouglass** [comment]
Yeah I think there is some work being done for theming the qqc2 stuff and updating the components where it makes sense.

**Comment by lduboeuf** [comment]
ok, we need to wait things becomes more "official". Is there any plan to switch from 15.04 to 16.04 templates ? Maybe by creating a "16.04" branch on templates repos ?

But my question was more is there an easy way to take an existing Qt desktop app and make it build for UT.

**Comment by JBBgameich** [comment]
Have a look at https://git.kaidan.im/kaidan/kaidan. We already did this process. The relevant files are clickable.json, some parts of CMakeLists.txt and utils/build-click.sh

**Comment by lduboeuf** [comment]
:+1 thank you,already bookmarked :). Maybe too complicated to automate the process entirely. At least we can have apparmor, .desktop and manifest files generated from clickable

**Comment by JBBgameich** [comment]
If you have a c++ part, building in clickable is absolutely neccesary so the binary is abi compatible with Ubuntu Touch. The script in kaidan does mostly fetch external dependencies,  which you don't need if you don't use them. It's not that complicated if you remove that part.

**Comment by lduboeuf** [comment]
ok, thank you. I close this issue for now
