### ISSUE TITLE
Can't build qml app with uppercase-character directory

### ISSUE THREAD

**Issue by userj** [bhdouglass/clickable#66]
Running clickable with a new pure-qml template (option 1), gives an error when trying to build the app.
```
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.
```
This was because the app was in a folder with an uppercase character. e.g. "/home/user/Downloads/app-dir"

After moving the app-dir to /home/user/app-dir, everything works as expected.

**Comment by bhdouglass** [comment]
That's weird, I'll look into it

**Comment by bhdouglass** [comment]
I can't seem to reproduce this error, do you have anything interesting in your clickable.json?

**Comment by userj** [comment]
@bhdouglass likewise, I don't seem to have this error again. Not sure what happened. Will let you know if it happens again.

**Comment by bhdouglass** [comment]
Sounds good, if it does happen again go ahead and open up another issue!
