### ISSUE TITLE
Pleass add an option to update target or click package without rebuilding all the binaries

### ISSUE THREAD

**Issue by zubozrout** [bhdouglass/clickable#68]
Hello,
I've been just trying to edit an existing application that has a lot of c++ code in it and it takes ages to check out if my single change in qml file worked as expected or if it does not.

Could you please add an option to clickable that would just update all the qml files in the target (build) directory without having to recompile all the binaries?

Thank you very much for anything that could help me out here :).

PS. Ubuntu SDK somehow detected if there was a change to the binary files and only rebuilt those if there was an update - but a simple manual option to do this would very much suffice for me.

**Comment by bhdouglass** [comment]
Usually I would suggest just not running the `clean` command, so doing `clickable kill build click-build install launch`. But last time I used that it was buggy (that could have just been with cmake, not sure about qmake). So my suggestion would be to try that command and see what happens.

**Comment by zubozrout** [comment]
@bhdouglass Hi, thank you very much for the tip, this seems to work. You are my hero :+1: 
But since this is possible it would be great to have a shortcut for it or certainly to have it mentioned somewhere in the docs.

**Comment by bhdouglass** [comment]
You can set this to be the default behavior by setting the `default` property: http://clickable.bhdouglass.com/en/latest/clickable-json.html#default

I'm not sure I want to advertise it because it doesn't work for all cases.
