### ISSUE TITLE
clickable behind proxy

### ISSUE THREAD

**Issue by lduboeuf** [bhdouglass/clickable#7]
hi,
wondering how easy it will be to "automate"  clickable setup behind corporate proxy, here is the steps i followed to make it work [link](https://forums.ubports.com/topic/452/guide-clickable-behind-corporate-proxy).

**Comment by bhdouglass** [comment]
I might be able to add an env var that you can set for this, but I might need to tweak the usdk-target script.

**Comment by bhdouglass** [comment]
@lduboeuf with the change from lxd to docker as the default, can you check if this is still an issue for you?

**Comment by lduboeuf** [comment]
that works just fine. thank you :)

**Comment by bhdouglass** [comment]
You're welcome!
