### ISSUE TITLE
Unable to find image 'clickable/ubuntu-sdk:16.04-armhf-nvidia' locally

### ISSUE THREAD

**Issue by jonnius** [bhdouglass/clickable#70]
I am trying to use nvidia-docker with the `--nvidia` option. But this is what I get:

```
clickable --nvidia
error: no devices/emulators found
Unable to find image 'clickable/ubuntu-sdk:16.04-armhf-nvidia' locally
docker: Error response from daemon: manifest for clickable/ubuntu-sdk:16.04-armhf-nvidia not found.
```

**Comment by bhdouglass** [comment]
There isn't a 16.04 container for nvidia just yet, I'll have to see about creating one.

**Comment by bhdouglass** [comment]
I just pushed an nvidia container up to dockerhub, let me know if that works for you (I haven't been able to test it out myself)!

**Comment by jonnius** [comment]
Thanks!
