### ISSUE TITLE
Arch package broken

### ISSUE THREAD

**Issue by nikalon** [bhdouglass/clickable#72]
Clickable from AUR (https://aur.archlinux.org/packages/clickable/) gives an error when installing:
```
Cloning into 'clickable'...
done.
==> Starting pkgver()...
==> Updated version: clickable 251.d125c7c-1
==> Sources are ready.
==> Making package: clickable 251.d125c7c-1 (Thu 05 Jul 2018 06:25:37 PM CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Entering fakeroot environment...
==> Starting package()...
install: cannot stat '/home/miguel/.cache/yay/clickable/src/clickable/clickable.py': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
Error making: clickable
```

In the `PKGBUILD` file it seems that it's trying to install `clickable.py` from the root directory of the project but it no longer exists.

**Comment by bhdouglass** [comment]
@tydell can you take a look at this?

**Comment by tydell** [comment]
I will update the package in a few hours

**Comment by bhdouglass** [comment]
Thank you!

**Comment by bhdouglass** [comment]
@tydell this might be related to #75, I've fixed the issue for a pip install, so I'm thinking that could help you.

**Comment by Jujuyeh** [comment]
I managed to install clickable changing the PKGBUILD file:

Where
```
package() {

mkdir -p $pkgdir/usr/bin
install -m755 -t $pkgdir/usr/bin/ $srcdir/$pkgname/clickable.py
}
```

was changed to
```
package() {

mkdir -p $pkgdir/usr/bin
install -m755 -t $pkgdir/usr/bin/ $srcdir/$pkgname/clickable-dev
}
```

**Comment by ellypsis** [comment]
I think this issue can be closed.
I just installed clickable, and it's working fine

**Comment by bhdouglass** [comment]
@ellypsis thanks for testing!

@tydell would it make sense to have the arch package install using pip? That might simplify things.
