### ISSUE TITLE
unable to install adicional packages to docker container

### ISSUE THREAD

**Issue by johangm90** [bhdouglass/clickable#74]
i need to install Chinese fonts and mp3 decoder in order to test my app i don't have a phone so i use the clickable --desktop option to test it but my app don't work properly.

i tried to access the container this way:
sudo docker exec -i -t f5be33120xxx /bin/bash
but cant run sudo apt install in it...

Any workaround?

**Comment by bhdouglass** [comment]
You can use the `dependencies` field in your clickable.json to have clickable automatically install packages in your docker container for you: http://clickable.bhdouglass.com/en/latest/clickable-json.html#dependencies

Here is an example of it in action: https://github.com/UbuntuOpenStore/openstore-app/blob/master/clickable.json#L4

**Comment by johangm90** [comment]
Thank you!

**Comment by bhdouglass** [comment]
You're welcome!
