### ISSUE TITLE
Unable to find image '...' locally

### ISSUE THREAD

**Issue by balcy** [bhdouglass/clickable#76]
I'm not sure if this is a clickable problem or sth. with my docker installation:

- in the clickable.json file there is a dependency that cannot be installed in the container (e.g. due to conflicts, other problems)
- for demonstration I used `"dependencies": ["doesNotExist"]`
- `clickable`
- then it says: 
```Generating new docker image
Sending build context to Docker daemon  3.072kB
Step 1/3 : FROM clickable/ubuntu-sdk:16.04-amd64
 ---> 4b7e1af25be8
Step 2/3 : RUN echo set debconf/frontend Noninteractive | debconf-communicate && echo set debconf/priority critical | debconf-communicate
---> Using cache
---> b17b8df29e2a
Step 3/3 : RUN apt-get update && apt-get install -y --force-yes --no-install-recommends  doesNotExist && apt-get clean
 ---> Running in 2d561d879686
```
At the end there is the error:
```E: Unable to locate package doesNotExist
The command '/bin/sh -c apt-get update && apt-get install -y --force-yes --no-install-recommends  doesNotExist && apt-get clean' returned a non-zero code: 100
Command '['docker', 'build', '-t', 'clickable/ubuntu-sdk:16.04-amd64-383d2ea0-6c68-4686-8628-a1a891fec5fd', '.']' returned non-zero exit status 100.
```
- until here it was expected like this, but if I run `clickable` again, the output is
```
Checking dependencies
Dependencies already setup
Copied files to temp directory for click building
Unable to find image 'clickable/ubuntu-sdk:16.04-amd64-383d2ea0-6c68-4686-8628-a1a891fec5fd' locally
docker: Error response from daemon: manifest for clickable/ubuntu-sdk:16.04-amd64-383d2ea0-6c68-4686-8628-a1a891fec5fd not found.
See 'docker run --help'.
Command '['docker', 'run', '-v', '/home/chris/click/webappcy:/home/chris/click/webappcy', '-w', '/home/chris/click/webappcy/build', '-u', '1002', '-e', 'HOME=/tmp', '--rm', '-i', 'clickable/ubuntu-sdk:16.04-amd64-383d2ea0-6c68-4686-8628-a1a891fec5fd', 'bash', '-c', 'click build /home/chris/click/webappcy/build/tmp --no-validate']' returned non-zero exit status 125.
```
my current workaround for this is after correcting the non-working dependency, type `docker images` and connect an existing image id (same architecture and version) to the missing tag:
`docker tag 93644cb8933f clickable/ubuntu-sdk:16.04-amd64-383d2ea0-6c68-4686-8628-a1a891fec5fd`
this behavior for me is the same on vivid/xenial and on both armhf/amd64
clickable version: 4.3.3 (debian testing)

**Comment by bhdouglass** [comment]
Ah, ok, I'll have to put in a bug fix for this (it's definitely a clickable problem). Until that happens you can fix this by deleting the `.clickable` directory that gets created.

**Comment by bhdouglass** [comment]
Ok, this shouldn't happen in the latest release (4.3.5).

**Comment by balcy** [comment]
cool thank you !
