### ISSUE TITLE
Better dependency handling

### ISSUE THREAD

**Issue by nfsprodriver** [bhdouglass/clickable#80]
Currently it seems to be impossible to install packages into a container depending on packages from arch "all" (like libreoffice).
It also would be nice to have an option installing all dependencies automatically and maybe having the possibility to add ppas.

**Comment by bhdouglass** [comment]
You've got two options to overcome this: 1) Make a [custom docker container](http://clickable.bhdouglass.com/en/latest/clickable-json.html#docker-image), 2) use the option called [specificDependencies](http://clickable.bhdouglass.com/en/latest/clickable-json.html#dependencies). Both options can be confusing (unless you are familiar with docker) and both prevent you from using desktop mode so they aren't ideal. I do have plans to make this better and the idea of adding ppas makes sense :+1:

**Comment by bhdouglass** [comment]
This has been moved to gitlab: https://gitlab.com/clickable/clickable/issues/80
