### ISSUE TITLE
NVidia problem: Could not load UVM kernel module

### ISSUE THREAD

**Issue by jonnius** [bhdouglass/clickable#83]
I am running `clickable --nvidia -e` but this results in (the last 4 lines):
```
Successfully built package in './wifitransfer.sil_0.9_amd64.click'.
Skipping install, running in desktop mode
non-network local connections being added to access control list
nvidia-docker | 2018/08/15 08:11:54 Error: Could not load UVM kernel module. Is nvidia-modprobe installed?
```
nvidia-docker and nvidia-modprobe are installed. 

During the build the following message appears a dozen of times:
```
ERROR: ld.so: object '/opt/nvidia/$LIB/libGL.so.1' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```

Any idea?

**Comment by bhdouglass** [comment]
Unfortunately this sounds like an issue with nvidia-docker. Make sure you have v1 as v2 doesn't work very well.

**Comment by bhdouglass** [comment]
Yeah I recommend the nouveau driver since it works without weird things.
