### ISSUE TITLE
Framework & sdk confusion

### ISSUE THREAD

**Issue by mjsir911** [bhdouglass/clickable#85]
Hi, 

the `--xenial` flag does not seem to work with the cordova module.

I can submit a PR to fix this but I'm a bit confused, is the `config.sdk` supposed to be a version number aka `16.04` or a framework name aka `ubuntu-sdk-16.04`?

Thanks,

**Comment by bhdouglass** [comment]
That's actually going away soon, I've been reworking things for v5.0.0 and that's one thing I'm cleaning up

**Comment by bhdouglass** [comment]
This had been fixed in 5.0.0 which should be released soon-ish. If you want to check it out its on the `dev` branch
