### ISSUE TITLE
[Question] Where are clickable containers stored?

### ISSUE THREAD

**Issue by Arc676** [bhdouglass/clickable#86]
I'm writing an app for Ubuntu Touch OTA 4 (16.04). Until now, I was using the 15.04 SDK. With the `--xenial` flag, `clickable` started downloading the 16.04 files.

However, I was running low on disk space. The archives were downloaded properly, but the installation failed during extraction. I think this has caused some problems and I'd like to delete these files and repeat the installation now that I have freed up disk space. I'd also like to move them to a different partition, but I need to know where the files are in order to do this.

### Notes

I get these warnings when running with the 16.04 container but not with the 15.04 one. The one about performance also only appears with 16.04, but this is probably a separate issue.
```
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-'
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
libGL error: failed to open drm device: No such file or directory
libGL error: failed to load driver: i965
[PERFORMANCE]: Last frame took 40 ms to render.
```

The application does ultimately run, but it doesn't work when I try to install it on my UT device. It crashes before the application UI even appears.

**Comment by bhdouglass** [comment]
Clickable just uses docker underneath, so you can use the various docker prune command to cleanup disk space: https://stackoverflow.com/questions/32723111/how-to-remove-old-and-unused-docker-images
As for the app not running on your device, you may be trying to runs 16.04 compiled app on a 15.04 device. It sounds like you are running the unreleased code from github, so you can use the `--vivid` flag to compile in a 15.04 container.

**Comment by Arc676** [comment]
The device is running OTA4 (devel channel). The application crashed when I didn't pass `--xenial` as well, as it defaulted to the 15.04 container.

**Comment by Arc676** [comment]
I'll note that the error messages appear even with the installation done properly though.
```
QStandardPaths: error creating runtime directory /tmp/runtime-: Permission denied
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
libGL error: failed to open drm device: No such file or directory
libGL error: failed to load driver: i965
[PERFORMANCE]: Last frame took 36 ms to render.
```

**Comment by bhdouglass** [comment]
Sounds good, I'm glad you were able to sort that out!
