### ISSUE TITLE
Remarks for Archlinux installation

### ISSUE THREAD

**Issue by ellypsis** [bhdouglass/clickable#88]
I encountered several issue trying to setup clickable on my ArchLinux environment.
- Cookiecutter couldn't be find.
Your need to run `easy_install cookiecutter` after installing it to "import" it in Python
- Xorg permission.
you need to allow clickable to connect to the display. I used xhost : 
`xhost +local:clickable`

I don't know if it has its place in the readme, but it could be really useful for Archlinux user not familiar with docker and programming.

**Comment by ellypsis** [comment]
Cookiecutter was installed as dependency, I but had to run `easy_install cookiecutter` in terminal before I could use it.
And for xhost, I didn't have this warning.

**Comment by bhdouglass** [comment]
It might make sense to leave a comment over on AUR letting the packages' author know about your cookiecutter issues. As for xhost, it must not have warned you since it sounds like you already have it installed. I'll make a note of it in the docs.

**Comment by ellypsis** [comment]
xhost wasn't installed, It's why I had an error concerning Xorg, something like "can't connect to server disply: 0", and no warning from clickable was prompted.

**Comment by bhdouglass** [comment]
Do you mind posting the full output from clickable when xhost isn't installed?

**Comment by ellypsis** [comment]
I couldn't manage to trigger the error. Maybe because I installed xhost to solve it.
I pretty sure that the error was `cannot connect to X server :0.0` (found this error in [Xhost - Archwiki](https://wiki.archlinux.org/index.php/Xhost)).
Now, when I remove xhost, I have the warning that xhost is not installed.

**Comment by bhdouglass** [comment]
Ok, so the warning is showing without xhost. I've added a short blub to the docs about archlinux users needing to use xhost (which will go live with v5.0.0). So I'm going to close this issue out unless you have any other issues.
