### ISSUE TITLE
[5.0.0] qmlscene kill, kills late in the process

### ISSUE THREAD

**Issue by cibersheep** [bhdouglass/clickable#89]
- Plug device
- kee app open in device
- run clickable

App stays open on device. App gets build and compiled in computer. App closes in device. Sometimes app doesn't open in device.

The app is killed late in the process and get installed and opened too quickly. Therefore, sometimes stays closed

**Comment by bhdouglass** [comment]
Thanks for testing! I'll swap it back to being the first thing run.

**Comment by cibersheep** [comment]
The rest I have used works perfectly :)
- logs
- xenial install
- desktop

**Comment by bhdouglass** [comment]
I just pushed a fix for this, let me know how that works!
