### ISSUE TITLE
pure-qml-qmake is not acccepted

### ISSUE THREAD

**Issue by altpapier** [bhdouglass/clickable#9]
If I set pure-qml-qmake as template, I get the error:
"pure-qml-qmake" is not a valid template (pure-qml-cmake, qmake, pure-qml-cmake, cmake, custom, cordova, pure, python)

The following list does contain PURE_QML_CMAKE twice
 
templates = [PURE_QML_CMAKE, QMAKE, PURE_QML_CMAKE, CMAKE, CUSTOM, CORDOVA, PURE, PYTHON]

**Comment by bhdouglass** [comment]
Sorry about that! Thanks to NeoTheThird this is now fixed.
