### ISSUE TITLE
app build fails with xenial nvidia image

### ISSUE THREAD

**Issue by jonnius** [bhdouglass/clickable#91]
Can be reproduced with nvidia-docker installed and a nvidia driver with:

- `clickable init`, choose C++/cmake 
- run `clickable --nvidia --xenial -e`

result: [error log](https://pastebin.com/bBcVpbCS)

**Comment by bhdouglass** [comment]
I believe this isn't a nvidia specific issue, but probably an issue with the packaging for desktop mode. Try out the latest version of the docker container, should fix this problem: `clickable update-docker --xenial`

**Comment by bhdouglass** [comment]
It should be using 16.04 when you pass it --xenial, regardless of passing --nvidia. Can you post the full output from `clickable --xenial --nvidia --desktop` ?

**Comment by jonnius** [comment]
Sorry, it seems I was confused last time about vivid/xenial. Anyway here is the full output after a update to the xenial container: https://pastebin.com/LixzZXLb

**Comment by bhdouglass** [comment]
Can you compile your app with `clickable --xenial --desktop`. It'll fail to display, but I'm mostly curious if it will compile.

**Comment by jonnius** [comment]
Basically the same: https://pastebin.com/uqWeKK39
I am on 18.04, if that is important.

**Comment by bhdouglass** [comment]
Oh it looks like you have some dependencies in use, so can you try removing the `.clickable` directory and try again?

**Comment by bhdouglass** [comment]
It's doubtful that it will change anything but can you try running this command? `docker pull clickable/ubuntu-sdk:16.04-amd64-nvidia` and then retry with `clickable --xenial --desktop`?

**Comment by bhdouglass** [comment]
I didn't think it would do anything, thanks for confirming!

I attempted to replicate this myself, but nvidia-docker doesn't seem to want to work with ubuntu bionic, so I didn't get very far with that. Are you able to use the nouveau drivers?

**Comment by jonnius** [comment]
I am on Ubuntu Bionic. I installed nvidia-docker back when I was on Xenial. Maybe that is the reason...

Yes, working on the nouveau driver works. And as I have stated in one of the previous posts, the app even started without the `--nvidia` using the nvidia driver.

**Comment by bhdouglass** [comment]
Ah, so sounds like you are using the nouveau drivers and not the nvidia ones. Then you don't need to use the `--nvidia` flag

**Comment by jonnius** [comment]
Nope, the proprietary driver nvidia-390 is in use: 
```
$ prime-select query
nvidia
```
I don't know why it works without `--nvidia`.

**Comment by bhdouglass** [comment]
Oh weird, so it works with the app popping up and everything when doing `clickable --xenial --desktop` and no `--nvidia` ?

**Comment by bhdouglass** [comment]
weird, but I won't question if it works! Maybe prime is doing something different?

**Comment by jonnius** [comment]
When I tried first last year, that didn't work. Maybe it is prime, because those messages mention some intel drivers: 
```
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
libGL error: failed to open drm device: No such file or directory
libGL error: failed to load driver: i965
```
Anyway. Good to know it works with nvidia driver and without nvidia-docker...

**Comment by bhdouglass** [comment]
yes definitely good to know that! Thanks for testing this with me.
